### ISSUE TITLE
Import Error: No module named request

### ISSUE THREAD

**Issue by philwild2** [sangaline/wayback-machine-scraper#12]
Hi there

When running this I get the error:

Traceback (most recent call last):
  File "/usr/local/bin/wayback-machine-scraper", line 5, in <module>
    from wayback_machine_scraper.__main__ import main
  File "/usr/local/lib/python2.7/site-packages/wayback_machine_scraper/__main__.py", line 7, in <module>
    from .mirror_spider import MirrorSpider
  File "/usr/local/lib/python2.7/site-packages/wayback_machine_scraper/mirror_spider.py", line 7, in <module>
    from scrapy_wayback_machine import WaybackMachineMiddleware
  File "/usr/local/lib/python2.7/site-packages/scrapy_wayback_machine/__init__.py", line 3, in <module>
    from urllib.request import pathname2url
ImportError: No module named request

It looks like it's pointing to Python 2.7...but when I type "python --version" I get Python 3.7. Shouldn't this run with either though? Thanks.

**Comment by moseswynn** [comment]
If you have both Python2 and Python3 installed, you may need to use pip3 instead of pip to install. What is your output for `ls -l /usr/bin | grep python`?

**Comment by sangaline** [comment]
It looks like Python 2 support was broken in sangaline/scrapy-wayback-machine#2. I just published a fix in sangaline/scrapy-wayback-machine#6.
